/* sd_il2cpp_offsets.h -- GENERATED by tools/derive_il2cpp_hooks.py. Do not edit.
 * Source: dump.cs verified against libil2cpp.so (RVA-Offset delta 0x4000
 * matches the il2cpp section). Every RVA is bounds-checked into an executable
 * section and checked for identical-code folding. W0/W1 are the first two
 * instruction words at each target, verified before any hook is written. */
#ifndef SD_IL2CPP_OFFSETS_H
#define SD_IL2CPP_OFFSETS_H

/* Instance field offsets (from the object/struct start, as dump.cs gives them). */
#define SD_FLD_PED_pointerEnter 0x20u   /* PointerEventData.<pointerEnter>k__BackingField */
#define SD_FLD_PED_pointerPress 0x28u   /* PointerEventData.m_PointerPress */
#define SD_FLD_PED_rawPointerPress 0x38u   /* PointerEventData.<rawPointerPress>k__BackingField */
#define SD_FLD_PED_pointerDrag 0x40u   /* PointerEventData.<pointerDrag>k__BackingField */
#define SD_FLD_PED_pointerClick 0x48u   /* PointerEventData.<pointerClick>k__BackingField */
#define SD_FLD_PED_currentRaycast 0x50u   /* PointerEventData.<pointerCurrentRaycast>k__BackingField */
#define SD_FLD_PED_eligibleForClick 0xF8u   /* PointerEventData.<eligibleForClick>k__BackingField */
#define SD_FLD_PED_pointerId 0x100u   /* PointerEventData.<pointerId>k__BackingField */
#define SD_FLD_PED_position 0x104u   /* PointerEventData.<position>k__BackingField */
#define SD_FLD_PED_pressPosition 0x114u   /* PointerEventData.<pressPosition>k__BackingField */
#define SD_FLD_PED_useDragThreshold 0x144u   /* PointerEventData.<useDragThreshold>k__BackingField */
#define SD_FLD_PED_dragging 0x145u   /* PointerEventData.<dragging>k__BackingField */
#define SD_FLD_PED_button 0x148u   /* PointerEventData.<button>k__BackingField */
#define SD_FLD_RR_gameObject 0x0u   /* RaycastResult.m_GameObject */
#define SD_FLD_BIM_eventSystem 0x38u   /* BaseInputModule.m_EventSystem */
#define SD_FLD_ES_dragThreshold 0x3Cu   /* EventSystem.m_DragThreshold */
#define SD_FLD_OB_cachedPtr 0x10u   /* Object.m_CachedPtr */
#define SD_FLD_CSB_character 0x20u   /* CharacterSelectionButton.m_character */

/* void SetInt(string key, int value) */
#define SD_IL2CPP_PP_SetInt_RVA 0x2181E50u
#define SD_IL2CPP_PP_SetInt_W0  0xa9bf4ffeu
#define SD_IL2CPP_PP_SetInt_W1  0x97fffeefu
#define SD_IL2CPP_PP_SetInt_ABSENT 0

/* int GetInt(string key, int defaultValue) */
#define SD_IL2CPP_PP_GetInt2_RVA 0x2181EA8u
#define SD_IL2CPP_PP_GetInt2_W0  0xd10143ffu
#define SD_IL2CPP_PP_GetInt2_W1  0xa90357feu
#define SD_IL2CPP_PP_GetInt2_ABSENT 0

/* PP_GetInt1: NOT IN THIS BUILD -- int GetInt(string key)
 * PROVEN ABSENT: its class has no method of that name (stripped), so
 * nothing in this build can call it and leaving it unhooked is safe. */
#define SD_IL2CPP_PP_GetInt1_RVA 0u
#define SD_IL2CPP_PP_GetInt1_W0  0u
#define SD_IL2CPP_PP_GetInt1_W1  0u
#define SD_IL2CPP_PP_GetInt1_ABSENT 1

/* PP_SetFloat: NOT IN THIS BUILD -- void SetFloat(string key, float value)
 * PROVEN ABSENT: its class has no method of that name (stripped), so
 * nothing in this build can call it and leaving it unhooked is safe. */
#define SD_IL2CPP_PP_SetFloat_RVA 0u
#define SD_IL2CPP_PP_SetFloat_W0  0u
#define SD_IL2CPP_PP_SetFloat_W1  0u
#define SD_IL2CPP_PP_SetFloat_ABSENT 1

/* PP_GetFloat2: NOT IN THIS BUILD -- float GetFloat(string key, float defaultValue)
 * PROVEN ABSENT: its class has no method of that name (stripped), so
 * nothing in this build can call it and leaving it unhooked is safe. */
#define SD_IL2CPP_PP_GetFloat2_RVA 0u
#define SD_IL2CPP_PP_GetFloat2_W0  0u
#define SD_IL2CPP_PP_GetFloat2_W1  0u
#define SD_IL2CPP_PP_GetFloat2_ABSENT 1

/* void SetString(string key, string value) */
#define SD_IL2CPP_PP_SetString_RVA 0x2182064u
#define SD_IL2CPP_PP_SetString_W0  0xa9bf4ffeu
#define SD_IL2CPP_PP_SetString_W1  0x97fffedau
#define SD_IL2CPP_PP_SetString_ABSENT 0

/* string GetString(string key, string defaultValue) */
#define SD_IL2CPP_PP_GetString2_RVA 0x21820BCu
#define SD_IL2CPP_PP_GetString2_W0  0xd10343ffu
#define SD_IL2CPP_PP_GetString2_W1  0xa90b57feu
#define SD_IL2CPP_PP_GetString2_ABSENT 0

/* string GetString(string key) */
#define SD_IL2CPP_PP_GetString1_RVA 0x21823C0u
#define SD_IL2CPP_PP_GetString1_W0  0xa9be57feu
#define SD_IL2CPP_PP_GetString1_W1  0xa9014ff4u
#define SD_IL2CPP_PP_GetString1_ABSENT 0

/* bool HasKey(string key) */
#define SD_IL2CPP_PP_HasKey_RVA 0x2182408u
#define SD_IL2CPP_PP_HasKey_W0  0xd10143ffu
#define SD_IL2CPP_PP_HasKey_W1  0xf9001bfeu
#define SD_IL2CPP_PP_HasKey_ABSENT 0

/* void DeleteKey(string key) */
#define SD_IL2CPP_PP_DeleteKey_RVA 0x21825B8u
#define SD_IL2CPP_PP_DeleteKey_W0  0xd10143ffu
#define SD_IL2CPP_PP_DeleteKey_W1  0xf9001bfeu
#define SD_IL2CPP_PP_DeleteKey_ABSENT 0

/* void Save() */
#define SD_IL2CPP_PP_Save_RVA 0x218275Cu
#define SD_IL2CPP_PP_Save_W0  0xa9bf4ffeu
#define SD_IL2CPP_PP_Save_W1  0xd00021d3u
#define SD_IL2CPP_PP_Save_ABSENT 0

/* int get_touchCount() */
#define SD_IL2CPP_IN_get_touchCount_RVA 0x21C53B4u
#define SD_IL2CPP_IN_get_touchCount_W0  0xa9bf4ffeu
#define SD_IL2CPP_IN_get_touchCount_W1  0x90001fd3u
#define SD_IL2CPP_IN_get_touchCount_ABSENT 0

/* Vector3 get_mousePosition() */
#define SD_IL2CPP_IN_get_mousePosition_RVA 0x21C4EDCu
#define SD_IL2CPP_IN_get_mousePosition_W0  0xd10083ffu
#define SD_IL2CPP_IN_get_mousePosition_W1  0xa9014ffeu
#define SD_IL2CPP_IN_get_mousePosition_ABSENT 0

/* bool GetMouseButton(int button) */
#define SD_IL2CPP_IN_GetMouseButton_RVA 0x21C4CFCu
#define SD_IL2CPP_IN_GetMouseButton_W0  0xf81e0ffeu
#define SD_IL2CPP_IN_GetMouseButton_W1  0xa9014ff4u
#define SD_IL2CPP_IN_GetMouseButton_ABSENT 0

/* bool GetMouseButtonDown(int button) */
#define SD_IL2CPP_IN_GetMouseButtonDown_RVA 0x21C4D38u
#define SD_IL2CPP_IN_GetMouseButtonDown_W0  0xf81e0ffeu
#define SD_IL2CPP_IN_GetMouseButtonDown_W1  0xa9014ff4u
#define SD_IL2CPP_IN_GetMouseButtonDown_ABSENT 0

/* bool GetMouseButtonUp(int button) */
#define SD_IL2CPP_IN_GetMouseButtonUp_RVA 0x21C4D74u
#define SD_IL2CPP_IN_GetMouseButtonUp_W0  0xf81e0ffeu
#define SD_IL2CPP_IN_GetMouseButtonUp_W1  0xa9014ff4u
#define SD_IL2CPP_IN_GetMouseButtonUp_ABSENT 0

/* Touch GetTouch(int index) */
#define SD_IL2CPP_IN_GetTouch_RVA 0x21C4DB0u
#define SD_IL2CPP_IN_GetTouch_W0  0xd101c3ffu
#define SD_IL2CPP_IN_GetTouch_W1  0xa90557feu
#define SD_IL2CPP_IN_GetTouch_ABSENT 0

/* bool get_touchSupported() */
#define SD_IL2CPP_IN_get_touchSupported_RVA 0x21C5348u
#define SD_IL2CPP_IN_get_touchSupported_W0  0xa9bf4ffeu
#define SD_IL2CPP_IN_get_touchSupported_W1  0x90001fd3u
#define SD_IL2CPP_IN_get_touchSupported_ABSENT 0

/* Touch[] get_touches() */
#define SD_IL2CPP_IN_get_touches_RVA 0x21C553Cu
#define SD_IL2CPP_IN_get_touches_W0  0xd10383ffu
#define SD_IL2CPP_IN_get_touches_W1  0xf90053feu
#define SD_IL2CPP_IN_get_touches_ABSENT 0

/* int get_width() */
#define SD_IL2CPP_SC_get_width_RVA 0x21686CCu
#define SD_IL2CPP_SC_get_width_W0  0xa9bf4ffeu
#define SD_IL2CPP_SC_get_width_W1  0x900022b3u
#define SD_IL2CPP_SC_get_width_ABSENT 0

/* private bool CanAnalyticsEventsBeCollected(IAnalyticsEvent analyticsEvent) */
#define SD_IL2CPP_AN_CanCollect_RVA 0x193B150u
#define SD_IL2CPP_AN_CanCollect_W0  0xf81d0ffeu
#define SD_IL2CPP_AN_CanCollect_W1  0xa90157f6u
#define SD_IL2CPP_AN_CanCollect_ABSENT 0

/* int get_height() */
#define SD_IL2CPP_SC_get_height_RVA 0x21686F4u
#define SD_IL2CPP_SC_get_height_W0  0xa9bf4ffeu
#define SD_IL2CPP_SC_get_height_W1  0x900022b3u
#define SD_IL2CPP_SC_get_height_ABSENT 0

/* Vector3 get_acceleration() */
#define SD_IL2CPP_IN_get_acceleration_RVA 0x21C53DCu
#define SD_IL2CPP_IN_get_acceleration_W0  0xd10083ffu
#define SD_IL2CPP_IN_get_acceleration_W1  0xa9014ffeu
#define SD_IL2CPP_IN_get_acceleration_ABSENT 0

/* public void set_enabled(bool value) */
#define SD_IL2CPP_GY_set_enabled_RVA 0x21C4710u
#define SD_IL2CPP_GY_set_enabled_W0  0xa9be57feu
#define SD_IL2CPP_GY_set_enabled_W1  0xa9014ff4u
#define SD_IL2CPP_GY_set_enabled_ABSENT 0

/* public bool get_enabled() */
#define SD_IL2CPP_GY_get_enabled_RVA 0x21C46D4u
#define SD_IL2CPP_GY_get_enabled_W0  0xf81e0ffeu
#define SD_IL2CPP_GY_get_enabled_W1  0xa9014ff4u
#define SD_IL2CPP_GY_get_enabled_ABSENT 0

/* bool get_supportsGyroscope() */
#define SD_IL2CPP_SI_supportsGyroscope_RVA 0x219152Cu
#define SD_IL2CPP_SI_supportsGyroscope_W0  0xa9bf4ffeu
#define SD_IL2CPP_SI_supportsGyroscope_W1  0x90002173u
#define SD_IL2CPP_SI_supportsGyroscope_ABSENT 0

/* protected void ProcessTouchPress(PointerEventData pointerEvent, bool pressed, bool released) */
#define SD_IL2CPP_UI_SIM_ProcessTouchPress_RVA 0x228EFF4u
#define SD_IL2CPP_UI_SIM_ProcessTouchPress_W0  0x6dba23e9u
#define SD_IL2CPP_UI_SIM_ProcessTouchPress_W1  0xa9016ffeu
#define SD_IL2CPP_UI_SIM_ProcessTouchPress_ABSENT 0

/* protected void ProcessTouchPress(PointerEventData pointerEvent, bool pressed, bool released) */
#define SD_IL2CPP_UI_TIM_ProcessTouchPress_RVA 0x2290344u
#define SD_IL2CPP_UI_TIM_ProcessTouchPress_W0  0xfc1b0fe8u
#define SD_IL2CPP_UI_TIM_ProcessTouchPress_W1  0xf90007feu
#define SD_IL2CPP_UI_TIM_ProcessTouchPress_ABSENT 0

/* private void Press() */
#define SD_IL2CPP_UI_Button_Press_RVA 0x2247AD0u
#define SD_IL2CPP_UI_Button_Press_W0  0xf81e0ffeu
#define SD_IL2CPP_UI_Button_Press_W1  0xa9014ff4u
#define SD_IL2CPP_UI_Button_Press_ABSENT 0

/* public void OnClick() */
#define SD_IL2CPP_UI_CSB_OnClick_RVA 0x1176738u
#define SD_IL2CPP_UI_CSB_OnClick_W0  0xa9be57feu
#define SD_IL2CPP_UI_CSB_OnClick_W1  0xa9014ff4u
#define SD_IL2CPP_UI_CSB_OnClick_ABSENT 0

/* public void ShowPage(DialogPageIdentifier identifier, object data, PageStackSystem.OnPageLoaded<DialogPage> onLoadedCallback) */
#define SD_IL2CPP_UI_Dialog_ShowPage_RVA 0x10C5C78u
#define SD_IL2CPP_UI_Dialog_ShowPage_W0  0xf81c0ffeu
#define SD_IL2CPP_UI_Dialog_ShowPage_W1  0xa9015ff8u
#define SD_IL2CPP_UI_Dialog_ShowPage_ABSENT 0

/* public void PurchaseCharacter() */
#define SD_IL2CPP_UI_CSP_PurchaseCharacter_RVA 0x10F45A4u
#define SD_IL2CPP_UI_CSP_PurchaseCharacter_W0  0xf81d0ffeu
#define SD_IL2CPP_UI_CSP_PurchaseCharacter_W1  0xa90157f6u
#define SD_IL2CPP_UI_CSP_PurchaseCharacter_ABSENT 0

/* public string get_name() */
#define SD_IL2CPP_OB_get_name_RVA 0x218E1E0u
#define SD_IL2CPP_OB_get_name_W0  0x14000001u
#define SD_IL2CPP_OB_get_name_W1  0xd10183ffu
#define SD_IL2CPP_OB_get_name_ABSENT 0

/* float get_deltaTime() */
#define SD_IL2CPP_TI_get_deltaTime_RVA 0x217C038u
#define SD_IL2CPP_TI_get_deltaTime_W0  0xa9bf4ffeu
#define SD_IL2CPP_TI_get_deltaTime_W1  0xb0002213u
#define SD_IL2CPP_TI_get_deltaTime_ABSENT 0

/* float get_unscaledDeltaTime() */
#define SD_IL2CPP_TI_get_unscaledDeltaTime_RVA 0x2191B54u
#define SD_IL2CPP_TI_get_unscaledDeltaTime_W0  0xa9bf4ffeu
#define SD_IL2CPP_TI_get_unscaledDeltaTime_W1  0x90002173u
#define SD_IL2CPP_TI_get_unscaledDeltaTime_ABSENT 0

/* float get_realtimeSinceStartup() */
#define SD_IL2CPP_TI_get_realtimeSinceStartup_RVA 0x21909F0u
#define SD_IL2CPP_TI_get_realtimeSinceStartup_W0  0xa9bf4ffeu
#define SD_IL2CPP_TI_get_realtimeSinceStartup_W1  0xb0002173u
#define SD_IL2CPP_TI_get_realtimeSinceStartup_ABSENT 0

/* float get_timeScale() */
#define SD_IL2CPP_TI_get_timeScale_RVA 0x2191C2Cu
#define SD_IL2CPP_TI_get_timeScale_W0  0xa9bf4ffeu
#define SD_IL2CPP_TI_get_timeScale_W1  0x90002173u
#define SD_IL2CPP_TI_get_timeScale_ABSENT 0

/* int get_frameCount() */
#define SD_IL2CPP_TI_get_frameCount_RVA 0x2186530u
#define SD_IL2CPP_TI_get_frameCount_W0  0xa9bf4ffeu
#define SD_IL2CPP_TI_get_frameCount_W1  0xf00021b3u
#define SD_IL2CPP_TI_get_frameCount_ABSENT 0

#endif /* SD_IL2CPP_OFFSETS_H */
